### ISSUE TITLE
No song/track found with given query.

### ISSUE THREAD

**Issue by FrostSTeeL** [shahriyardx/dismusic#1]
Hello,
Bot worked great until a week ago. I updated it to the latest version but, i get the error in the title anytime i try to use it. It doesn't matter if i give the exact link to the bot or not.

**Comment by shahriyardx** [comment]
> Hello,
> Bot worked great until a week ago. I updated it to the latest version but, i get the error in the title anytime i try to use it. It doesn't matter if i give the exact link to the bot or not.

Can you provide more information so I can reproduce this issue?

**Comment by FrostSTeeL** [comment]
My bot's code and the screenshot of the error im getting is below, is there anything else i can provide?

```
import discord
import requests
from discord.ext import commands, tasks

from env import PASSWORD, TOKEN

bot = commands.Bot(command_prefix='!')

bot.lavalink_nodes = [
    {
        'host': 'lava.link',
        'port': 80,
        'password': PASSWORD,
    }
]


@bot.event
async def on_ready():
    change_status.start()
    bot.load_extension('dismusic')
    print('Valhalla calling..')


@tasks.loop(minutes=15)
async def change_status():
    r = requests.get('https://www.google.com/')
    print(r)
    await bot.change_presence(
        activity=discord.Activity(
            name=f'!play In Maidjan',
            type=1
        )
    )

bot.run(TOKEN)
```
![screenshot](https://user-images.githubusercontent.com/42972866/160790220-48f20c00-a3a6-49aa-8a36-cafbd901e869.jpg)

**Comment by shahriyardx** [comment]
I think the node is causing problem. Can you try using a different node

**Comment by FrostSTeeL** [comment]
> I think the node is causing problem. Can you try using a different node

Yes you were right, it was the node! Thank you!

edit: Is there any way we can implement an error message when the node fails?
